### ISSUE TITLE
Create an self-hosted filter on the interactive version

### ISSUE THREAD

**Issue by dkmbw** [cncf/landscape#1149]
Please add a filter to show which software can be completely built and run on self-hosted/on-premise datacenters

**Comment by dkmbw** [comment]
Alternatively following filters could be suggested:
* can be run on an airgapped network
* can be built on an airgapped network
* can be built only with opensource tools/systems
* can be run with only opensource-systems 
* can be run without license management system

perhaps this is easier to filter.

**Comment by dankohn** [comment]
Sorry for the long delay in my response. Note that adding new filters at this point is quite challenging, as we need to back-fill the information across 581 cards: https://landscape.cncf.io/category=provisioning,runtime,orchestration-management,app-definition-and-development,platform,serverless,observability-and-analysis&format=card-mode&grouping=category

However, nearly all of the open source projects will meet your criteria. They can be run on airgapped networks. They all depend on only open source components, so if you watch the build, you can locally cache any dependencies. None of them need license management systems.

That is these 338 cards: https://landscape.cncf.io/category=provisioning,runtime,orchestration-management,app-definition-and-development,platform,serverless,observability-and-analysis&format=card-mode&grouping=category&license=open-source

The only exception I see is items like https://landscape.cncf.io/selected=kops that is explicitly designed for installing on to AWS.

**Comment by dkmbw** [comment]
Well, Travis-CI is there, too. And you cannot self-host That as far as i am aware.

AND: Though most may be buildable and installable and runnable on an airgapped network, it is often not sustainable. Did you ever try to build and run Hadoop or Gitlab (just an example) on your virtual machine which is a current debian, centos or ubuntu lts? This is one HUGE undertaking, where every upgrade is an Major Painpoint.

From my POV the CNCF can not say it prevents an vendor-lockin when the opensource-software-vendors create an lockin where you cannot really build the software environment for yourself. 

It would be the next logical step to track and tag all Projects if they can be run and BUILT on an air-gapped network.

jm2c

**Comment by dankohn** [comment]
My understanding is that Travis is 100% open source so you could self-host, though no one bothers to do so because it is not competitive with the alternative offerings. If that's not the case, we'd remove the `repo_url` and show it as closed source.

I think you may be conflating support for an airgapped network with not being able to build for yourself. 100% of the open source projects listed on the landscape are buildable with only open source tools. You're correct that they often assume network access, but all of the software, dependencies, and build tools are available under an open source license.

By contrast, airgapping is an unusual special case, but many important projects support it. For example: https://www.google.com/search?q=kubernetes+airgap
