### ISSUE TITLE
Updates to Paas/Container Service

### ISSUE THREAD

**Issue by craigkj312** [cncf/landscape#122]
Cloud Engine is now called Compute Engine and Google also now has a Container Engine offering as well on their platform.

Amazon Web Services has a container service offering on their platform as well called Amazon EC2 Container Service (ECS).

Azure also has a container service as well just called Azure Container Service.

**Comment by dankohn** [comment]
Thanks. We're generally not creating additional entries for public clouds like Google and Microsoft that have container engines, storage solutions, load balancers, etc. because all of that is expected today from a top-tier public cloud.

We're not including GKE because we're not doing separate logos for each implementation of Kubernetes. Instead, we track them here: https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0

But we do appreciate the suggestions.
