### ISSUE TITLE
Deadline cutoff for 1.0

### ISSUE THREAD

**Issue by shawnpreissner** [cncf/landscape#219]
Will support all requests prior to this in the upcoming release. The subsequent issues filed will be processed for the next version. Thanks for all of the engagement and stay tuned for 1.0!

**Comment by shawnpreissner** [comment]
1.0 is out -> https://github.com/cncf/landscape#current-version

**Comment by tnir** [comment]
@shawnpreissner As 1.0 is out, is this issue to be closed?

**Comment by shawnpreissner** [comment]
@tnir I leave open until next rev is out, for a quick way to count net new GitHub requests between versions. Total issues aren't an accurate representation, since some open issues are longer term requests.

**Comment by sodabrew** [comment]
You might prefer the https://github.com/cncf/landscape/milestones feature in GitHub -- you can queue up a set of requests with a deadline / release date for each milestone as you go. When I'm running open source projects, I tend to keep 2 minor and 1 major versions open at a time and triage GitHub PRs / Issues into the appropriate Milestone so that reporters know where their ticket stands and when it is likely to land. Cheers!

**Comment by shawnpreissner** [comment]
Thanks all for the feedback! Closing as 1.1 has now released, check out the most recent version https://github.com/cncf/landscape#current-version
