### ISSUE TITLE
Add  PNG version (JPG has artifacts)

### ISSUE THREAD

**Issue by vacri** [cncf/landscape#230]
Please create a PNG version of the graph, which will avoid the ugly JPEG compression artifacts, and will likely also reduce the file size. PNG is more suitable than JPG for this kind of imagery.

**Comment by dankohn** [comment]
Thanks for the feedback. I used OS X Preview to convert the AI to PNGs at 300 and 450 px/in (attached).

File sizes:
PNG-300: 4.3 MB
PNG-450: 6.4 MB
JPG: 3.8 MB

I'm somewhat inclined to go with the 6.4 MB one, since people can always reduce it further if they need to. What do you think?

![cloudnativelandscape_latest-300](https://user-images.githubusercontent.com/3083270/34234632-4fa674e8-e5ba-11e7-86ef-7b2c782285c4.png)
![cloudnativelandscape_latest-450](https://user-images.githubusercontent.com/3083270/34234634-4fb2f894-e5ba-11e7-8515-f9e63548b4ba.png)

**Comment by vacri** [comment]
They look a lot nicer zoomed in now, awesome. Unfortunately I'm not 'an image guy' so I can't say much more on which one to go for, but I'd guess go for the larger, clearer version until someone with a stronger opinion comes along :)

Happy to have this ticket closed.

**Comment by dankohn** [comment]
It turns out the GitHub defaults to serving images of >5 MB as octet-stream rather than PNG, causing them to be downloaded by default.

But, saving the PNGs with only 256 colors makes them much smaller.

@alexcontini in the future, please produce PNGs instead of JPEGs. You may have more options in Photoshop. For me, I used OS X Preview to save the AI as a PNG as 450 px/in and then used the PNG Compressor app from the Mac App Store to reduce its size from 5.7 MB to 4.2 MB.

The image https://raw.githubusercontent.com/cncf/landscape/master/landscape/CloudNativeLandscape_latest.png now appears inline instead of downloading.
