### ISSUE TITLE
Execution of Heuristic Analysis

### ISSUE THREAD

**Issue by andreuxxxx** [cncf/landscape#3094]
@Hilzygift 

After our discussion on Thursday, May 22, Hilda will:

- [x] 1. Execute heuristic analysis running each one of the [10 Nielsen Heuristics](https://www.nngroup.com/articles/ten-usability-heuristics/)
- [ ] 2. Document findings on this [Notion template](https://www.notion.so/buoyantio/CNCF-Landscape-Heuristic-Evaluation-52a22cdbef204460b672df106b19de1a?pvs=4)
- [ ] 3. Customize the cover and introduction text on these sections to showcase this analysis is for the CNCF Landscape:

![Image](https://user-images.githubusercontent.com/3219456/227318711-4e751133-2ce4-4eef-abbe-3a42ab0f3d40.png)

**Comment by Hilzygift** [comment]
**What Is the CNCF Landscape?**

The Cloud Native Landscape project attempts to compile, categorize, and organize all open source projects and proprietary products that can benefit [[cloud native applications](https://www.aquasec.com/cloud-native-academy/cloud-native-applications/cloud-native-applications-101/)](https://www.aquasec.com/cloud-native-academy/cloud-native-applications/cloud-native-applications-101/).

The Cloud Native Computing Foundation (CNCF) maintains the cloud native landscape project. The project offers:

- A cloud native landscape map—an interactive map that consolidates all cloud native offerings and provides information about each category, product, and project. Check out the [[interactive map](https://landscape.cncf.io/)](https://landscape.cncf.io/), shown below.
- A cloud native trail map—an infographic that illustrates and explains a recommended process for implementing cloud native technology.
- A cloud native landscape guide—an online resource that explains the cloud native landscape map and defines six key categories.

The Cloud Native Landscape includes six categories, which we will describe in depth: Provisioning, Runtime, Orchestration, Observability, and Platform. [LINK](https://www.aquasec.com/cloud-native-academy/cloud-native-applications/cloud-native-landscape/#What-Are-the-6-Categories-of-the-Cloud-Native-Landscape?)

What Are the 6 Categories of the Cloud Native Landscape? Here are the six categories of the CNCF [[cloud native](https://www.aquasec.com/cloud-native-academy/cloud-native-applications/cloud-native-applications-101/)](https://www.aquasec.com/cloud-native-academy/cloud-native-applications/cloud-native-applications-101/) landscape:

- Provisioning—includes tools required for the foundational infrastructure upon which the cloud environments and supporting technologies will function.
- Runtime—includes tools necessary to run containers in cloud native environments.
- Orchestration & Management—includes the tools necessary to orchestrate and manage containers, applications, and resources.
- App Definition & Development—includes tools that enable applications to send and store data and tools needed to build and deploy applications.
- Observability & Analysis—includes tools that help monitor applications and alert stakeholders of any issue.
- Platforms—includes platforms that bundle multiple functionalities and tools. These platforms help configure and fine-tune multiple tools to help organizations more easily adopt cloud native technologies.[LINK](https://www.aquasec.com/cloud-native-academy/cloud-native-applications/cloud-native-landscape/#What-Are-the-6-Categories-of-the-Cloud-Native-Landscape?)

**Methodology**

The methodology used for the heuristic evaluation of the CNCF-Landscape website is Nielsen and Molich's heuristics. The domains used are:

#1: Visibility of System Status

#2: Match between system and the real world

#3: User control and freedom

#4: Consistency and standards

#5: Error prevention

#6: Recognition rather than recall

#7: Flexibility and efficiency of use

#8: Aesthetic and minimalist design

#9: Accessibility

#10: Help and documentation

**Goal**

Research a foundation to lay out a set of solutions to improve the current way to search, navigate and find relevant information on the Landscape.

**Demographic :** Devops Engineer, Software Architect, Backend Developer, Full-stack Developer, Frontend/Application Developer


**Heuristics Summary**

1. **Visibility of system status**

Users should be able to easily understand the current status of the system or application and its response to their actions. Here are the major findings I deduced while analyzing this domain on the CNCF-Landscape website:

The search field is not present which makes searching for an item difficult. The filters present are clumsy. Elements/molecule states are not too obvious. (having a severity score of 4-critical). 

Recommendation: Creating an affordance for search fields.

<img width="1799" alt="2 (2)" src="https://github.com/cncf/landscape/assets/80973395/8718b513-40ed-407f-b2f3-aedc37e738d2">


2.  **Match between system and the real world**

The language and concepts used in the system should match the language and concepts familiar to users. 
Major findings are:
The Navigation of the site is not situated properly. There is not a definite navigation bar at the top and the footer below (having a severity score of 3-Major). 

Recommendation: Making an obvious navigation of the website would create a proper understanding of user journey flows. The information architecture of the website would be improved therein.

<img width="1799" alt="22 (2)" src="https://github.com/cncf/landscape/assets/80973395/b0af0eb2-4963-4535-9856-f3736197d8b5">


3.  **User control and freedom**

Users should be able to easily undo or correct their actions and should not be forced into making irreversible actions. Having made an analysis of the site based on this domain, users would be able to undo or correct their actions.


4.  **Consistency and standards**

The system should follow established conventions and standards to ensure that users can easily understand how to use it. Major findings:
There isn't any menu bar or navigation bar except the one adopted for the mobile version which only shows the filter and tab switch between the landscape and the guide page. 

Recommendation: Suitable navigation bar should be made or designed for easy accessibility to menu options (having a severity score of 3-Major). The system maintains consistency in typography, But colours, layout, and some other components need to be worked on (having a severity score of 3-Major).

<img width="1799" alt="3 (1)" src="https://github.com/cncf/landscape/assets/80973395/64c5cb89-9dca-4ad1-a135-d2999cfb1221">

<img width="1810" alt="4" src="https://github.com/cncf/landscape/assets/80973395/04b082c6-7ce9-4217-973c-050506d32018">


5.  **Error prevention**

The system should be designed to prevent errors from occurring in the first place. After conducting a study of the website based on this domain, it was determined that error prevention is little in terms of severity. However, when implementing features that have to do with data production, input fields, options, and dialogues, this can be improved and properly considered.


6.  **Recognition rather than recall**

The system should minimise the need for users to remember information by providing visual cues or context. Major findings: Navigational items were present but there is still information overload to an extent, white space can be improved for easy scanning of elements. However, user research would provide more insight (having a severity score of 3-Major).

<img width="1799" alt="6 (1)" src="https://github.com/cncf/landscape/assets/80973395/34fee03c-925c-4ac4-a6db-89f5ba670984">


7.  **Flexibility and efficiency of use**

The system should cater to both novice and experienced users, providing shortcuts and accelerators for those who are more experienced. Major findings: Tool-tips that describe features and aid users in understanding the objective of the display were not properly effected, as clicking on them leads to the guide page. Recommendation: a prompter should be embedded to give an info of what the tool-tips means for that particulate component it is being used on (having a severity score of 2-Minor).

<img width="1799" alt="CNCF 7 (1)" src="https://github.com/cncf/landscape/assets/80973395/7186ee50-7ce6-4826-a67a-35827792e487">


8. **Aesthetic and minimalist design**

The system should be visually appealing and avoid extraneous information. The system's layout does not aid in concentrating attention on work flow. Information structures are not concise and limited scanning occurs. User research can help us churn out irrelevant information and retain the relevant ones. Some logos placed on the landscape are not clear and seem to be of small size. The colours used to guide the logo icons can be improved.

<img width="1799" alt="8 (1)" src="https://github.com/cncf/landscape/assets/80973395/922ffee4-beda-46c1-b3a6-dc6229f8e2aa">


9.  **Accessibility**

Amount of content displayed at a time is not all that reasonable, they are somewhat clustered most especially the technologies logo arrangement. Colours and text testing for accessibility according to the Web Content Accessibility Guidelines (WCAG) is highly encouraged to be done during the process of website redesign. For example: the tags used to display certain information about a particular organisation; the colours used can be improved.

<img width="1731" alt="CNCF Landscape (1)" src="https://github.com/cncf/landscape/assets/80973395/8531d0c5-7d9d-456d-b585-e123c9957ca1">


10.  **Help and documentation**

Proper documentation was done concerning the usage of the landscape. However, it can be improved upon with proper navigation.

<img width="1707" alt="10 (1)" src="https://github.com/cncf/landscape/assets/80973395/7b9b5cb8-2b00-4f59-9b99-4d0b96d1409c">

@andreuxxxx

**Comment by tegioz** [comment]
Thanks @andreuxxxx @Hilzygift!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
