### ISSUE TITLE
Migration to landscape2

### ISSUE THREAD

**Issue by tegioz** [cncf/landscape#3680]
Issue to track some tasks related to the migration to [landscape2](https://l2.cncf.io):

- [x] Merge #3679.
- [x] Stop landscape1 periodic jobs that commit to this repo (i.e. automated Crunchbase update by CNCF bot).
- [x] Unlink repository from Netlify site.

*(please feel free to add more as needed, this is a work in progress)*

We need to coordinate these tasks with the switch to landscape2.

/cc @caniszczyk @AndreyKozlov1984

**Comment by AndreyKozlov1984** [comment]
Let me cancel all periodic updates here for a landscape1 08.01.2024, 14:44, "Sergio Castaño Arteaga" ***@***.***>: Issue to track some tasks related to the migration to landscape2:Merge #3679.Stop landscape1 periodic jobs that commit to this repo (i.e. automated Crunchbase update by CNCF bot).Netlify GitHub app is no longer needed in this repository.(please feel free to add more as needed, this is a work in progress)We need to coordinate these tasks with the switch to landscape2./cc @caniszczyk @AndreyKozlov1984—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
