### ISSUE TITLE
Landscape modal should extend down lower

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#414]
It's distance from the top, left and right is good, but it should extend down lower. This is from the iPhone X:

![image](https://user-images.githubusercontent.com/3083270/37527788-3d688ac2-2909-11e8-86d2-e5b2c752be20.png)

**Comment by alexkontsevoy** [comment]
@dankohn the popup size is calculated in order to accomodate the address bar:

![image](https://user-images.githubusercontent.com/4476098/37604093-659d27ce-2bba-11e8-8788-38b2085fd5a1.png)

Address bar is forced to appear in landscape mode (at least, this was coded by @ZeusTheTrueGod , but does not seem to work unless you scroll up)

**Comment by dankohn** [comment]
Makes sense, I'll close.
