### ISSUE TITLE
Fluentd is not a log analytics product/tool

### ISSUE THREAD

**Issue by jkowall** [cncf/landscape#56]
It's a component of a stack, putting this in the logging category but not including logstash which is far more popular doesn't make a ton of sense.

**Comment by moderation** [comment]
Logstash is included in the logging category under the Elastic logo. From their website search metadata "We're the creators of Elasticsearch, Kibana, Beats, and Logstash...". I'll [link](https://github.com/cncf/landscape/issues/57#issuecomment-269869267) to @dankohn 's reply to your other objection rather than repeat it here.
