### ISSUE TITLE
Extract autocrop code into npm module

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#572]
Please create and publish an npm module at https://github.com/cncf/svg-autocrop that extracts out the autocropping code from the landscape.

**Comment by dankohn** [comment]
Please add more detailed comments for each function so I can follow better how it works.

**Comment by ZeusTheTrueGod** [comment]
Ok. Overall, we have multiple parts in the code:
1) at first we check if the SVG is valid for us, because certain "features" are not supported.
2) Then we convert SVG to PNG via a puppeteer based package, so extra setup may be required here.
3) Finally, we use jimp to spot the area which can be cropped. Also, we treat a white background as a transparent one for this puprpose
In the end, we just provide the proper viewport, so our transformation is pretty small. We also don't parse the SVG completely, because it may be a bit of malformed or whatever, we just use a string replacement to change the viewPort attribute.

**Comment by ZeusTheTrueGod** [comment]
@dankohn regarding the value 230, it is when we treat white color as a background. Some SVG files use a white background, which I want to ignore when making an autocrop (instead of an implicit transparent background).

other questions:
- can I link to this module via `cncf/svg-autocrop@master`, so no need to publish it to the npm at all ? I never published an npm module before and I am sure you or cncf company should own it if you choose to publish
- do I need to copy all the svg files to the repo or a current set of files is enough ?

**Comment by dankohn** [comment]
I'd like you to publish a real NPM module. You can share the keys wth me.

For #746, please copy the 2 SVGs I mention that caused problems in the
past, and add tests to confirm that they produce the output we expect. We
want to include tests in the NPM module. We don't need dozens of SVGs.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com
