### ISSUE TITLE
Add Exoscale to Infrastructure

### ISSUE THREAD

**Issue by ste-m** [cncf/landscape#71]
As a IaaS provider Exoscale should be added to the Infrastructure section. We have a PR ready for that if you like.

![2017-02-03 at 17 52 46](https://cloud.githubusercontent.com/assets/6197139/22600169/a7d29f3e-ea39-11e6-8bf0-d0ccdb37b161.png)

**Comment by ste-m** [comment]
the logo is included in our press kit in several formats, including vector:
https://www.exoscale.ch/static/files/press-kit.zip

**Comment by Hillside502** [comment]
Simple cloud computing for cloud native teams | Exoscale
https://www.exoscale.ch/

How Exoscale compares to DigitalOcean and Amazon
https://www.exoscale.ch/compare/

**Comment by shawnpreissner** [comment]
Hi @ste-m we really appreciate the request, however unfortunately, we are dealing with limited real estate in this format and due to a large number of hosting companies (doing great work), we have to allocate infrastructure to the largest overall infrastructure companies/members. I apologize again and know that Exoscale has good momentum. We hope to have a dynamic version soon which will allow us to add Exoscale to Infrastructure! Hope that clarifies and thanks for understanding.

**Comment by shawnpreissner** [comment]
Thanks @ste-m and @Hillside502, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
